In [5]:
pip install faker

Requirement already satisfied: faker in D:\Artificial intelligence\conda project\env\Lib\site-packages (40.23.0)
Requirement already satisfied: tzdata in D:\Artificial intelligence\conda project\env\Lib\site-packages (from faker) (2025.3)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import faker as Faker

In [7]:
from faker import Faker

fake = Faker()

names = [fake.first_name() for _ in range(500)]

print(names[:10])

['Mark', 'Jeremy', 'Karen', 'Susan', 'Steven', 'Max', 'Nicholas', 'Steven', 'Kimberly', 'Theodore']

In [8]:
names

['Mark',
 'Jeremy',
 'Karen',
 'Susan',
 'Steven',
 'Max',
 'Nicholas',
 'Steven',
 'Kimberly',
 'Theodore',
 'Bonnie',
 'Anthony',
 'Rebecca',
 'Andrea',
 'Nicole',
 'Samantha',
 'Mackenzie',
 'Nicholas',
 'Emma',
 'Antonio',
 'Jeffrey',
 'Stephanie',
 'Victoria',
 'Jared',
 'Fernando',
 'Kelsey',
 'Patricia',
 'Julie',
 'Christopher',
 'Brenda',
 'Brittany',
 'Shannon',
 'Steven',
 'Brenda',
 'John',
 'Penny',
 'James',
 'Jeffrey',
 'Jill',
 'John',
 'Eric',
 'Danny',
 'Lori',
 'Tina',
 'Meagan',
 'Patricia',
 'Donna',
 'Regina',
 'Kristi',
 'Rachel',
 'Jeffrey',
 'Scott',
 'Andrea',
 'Linda',
 'Brent',
 'Brian',
 'Kristen',
 'Randy',
 'Alexandra',
 'Tammy',
 'John',
 'James',
 'Donald',
 'Jeffrey',
 'Amanda',
 'Benjamin',
 'Patricia',
 'Caitlin',
 'Dominique',
 'John',
 'Kelly',
 'Jennifer',
 'Kayla',
 'Melissa',
 'Kathy',
 'Gwendolyn',
 'Brian',
 'Faith',
 'Laura',
 'Jean',
 'Meagan',
 'Allison',
 'Tiffany',
 'Teresa',
 'Andrea',
 'Tracy',
 'Roger',
 'Destiny',
 'Jessica',
 'Monica',
 'Aaron',
 'Jeremy',
 'Roy',
 'Gabriel',
 'Christopher',
 'Lisa',
 'Tonya',
 'Gabriel',
 'Diane',
 'Yvonne',
 'Manuel',
 'Jonathan',
 'Chelsea',
 'Robert',
 'Tina',
 'Christopher',
 'Joseph',
 'Diane',
 'Sophia',
 'Bruce',
 'Anne',
 'Sara',
 'William',
 'Sharon',
 'Karen',
 'Anita',
 'Danielle',
 'John',
 'Tammy',
 'Sarah',
 'Deanna',
 'Kaitlyn',
 'Laura',
 'David',
 'Gina',
 'Maxwell',
 'Jeffrey',
 'Kathleen',
 'Debbie',
 'Shawn',
 'Sara',
 'Erika',
 'John',
 'Molly',
 'Karen',
 'Jay',
 'Kelli',
 'Joseph',
 'Carol',
 'Nicholas',
 'Robert',
 'Tina',
 'Olivia',
 'Matthew',
 'Robert',
 'Matthew',
 'Evan',
 'Anthony',
 'Christina',
 'Lauren',
 'Alexander',
 'Joseph',
 'Morgan',
 'Meghan',
 'Monica',
 'Aaron',
 'Cathy',
 'Dennis',
 'Brittany',
 'Gregory',
 'Peter',
 'Daniel',
 'Monica',
 'Darrell',
 'Albert',
 'Tammy',
 'Kelsey',
 'Christie',
 'Erin',
 'Cameron',
 'Jeffrey',
 'Megan',
 'Shawn',
 'Kelsey',
 'Jill',
 'Samuel',
 'William',
 'Ricardo',
 'Michael',
 'Stephen',
 'Brittany',
 'Ashley',
 'Christopher',
 'Andrew',
 'Patricia',
 'Kimberly',
 'Christopher',
 'Steven',
 'Gina',
 'Sean',
 'David',
 'Brittney',
 'Margaret',
 'Rebecca',
 'Theresa',
 'Ashley',
 'Anthony',
 'Eric',
 'Denise',
 'Claudia',
 'Anthony',
 'Charles',
 'Kelly',
 'Robert',
 'Jessica',
 'Joseph',
 'Angela',
 'Andrea',
 'Deborah',
 'David',
 'Jesse',
 'Melanie',
 'Brandon',
 'Terrence',
 'Melissa',
 'Patricia',
 'Eric',
 'Regina',
 'Kristen',
 'Paul',
 'Kathryn',
 'Jennifer',
 'Steven',
 'Lauren',
 'Samuel',
 'Janet',
 'Emily',
 'Brandon',
 'Michael',
 'Tim',
 'Kimberly',
 'Regina',
 'Michael',
 'Jonathan',
 'Laura',
 'Kristi',
 'Michael',
 'Riley',
 'Albert',
 'Amanda',
 'Christina',
 'Joseph',
 'Maria',
 'Samantha',
 'Glenda',
 'Amy',
 'Frances',
 'Jesus',
 'Joseph',
 'Jennifer',
 'Stephanie',
 'Stephen',
 'Larry',
 'Kevin',
 'Cheryl',
 'Karen',
 'Mary',
 'Janet',
 'Jeffrey',
 'Sophia',
 'Stephanie',
 'Amanda',
 'Jeffrey',
 'Kevin',
 'Brittany',
 'Craig',
 'Wendy',
 'Johnny',
 'James',
 'Jeffrey',
 'Peggy',
 'Jessica',
 'Dominique',
 'Kevin',
 'Rachel',
 'Ashley',
 'Jasmine',
 'Linda',
 'Scott',
 'Anthony',
 'Daniel',
 'Donna',
 'Jennifer',
 'Crystal',
 'Michael',
 'Stephanie',
 'Jason',
 'Gina',
 'Sabrina',
 'Dawn',
 'Bruce',
 'Ricky',
 'Julie',
 'Crystal',
 'Eric',
 'Sarah',
 'Michelle',
 'Amanda',
 'Bailey',
 'Antonio',
 'Brianna',
 'James',
 'Michael',
 'Veronica',
 'Michael',
 'Angela',
 'Allen',
 'Jennifer',
 'Donna',
 'Daniel',
 'Rhonda',
 'Travis',
 'Lisa',
 'Corey',
 'Gabriel',
 'Jessica',
 'Amanda',
 'John',
 'Howard',
 'Melissa',
 'Tony',
 'Elizabeth',
 'Dominique',
 'Sara',
 'Mark',
 'Marcus',
 'John',
 'Paul',
 'Stacey',
 'Samantha',
 'Debbie',
 'William',
 'Jeffery',
 'Kayla',
 'Kim',
 'Wayne',
 'Christopher',
 'Samantha',
 'Melissa',
 'William',
 'Stacy',
 'Chelsea',
 'Jason',
 'Jennifer',
 'Renee',
 'Peter',
 'Douglas',
 'Nicholas',
 'Michael',
 'Jacob',
 'Craig',
 'Anthony',
 'Vickie',
 'Jessica',
 'Gina',
 'Jay',
 'Brandi',
 'Kendra',
 'Charles',
 'Rachel',
 'Brian',
 'Scott',
 'Alisha',
 'Brianna',
 'Kim',
 'Antonio',
 'Henry',
 'Helen',
 'Christina',
 'Leslie',
 'Wendy',
 'David',
 'Kayla',
 'Mary',
 'Charlene',
 'Christine',
 'Christopher',
 'Meghan',
 'Harry',
 'Amy',
 'Brandy',
 'Tina',
 'Jonathan',
 'Alex',
 'Kristen',
 'Sandy',
 'Lisa',
 'Faith',
 'Christian',
 'Debra',
 'Monica',
 'Donald',
 'Courtney',
 'Tanya',
 'Brooke',
 'Deanna',
 'Christopher',
 'Anthony',
 'Miguel',
 'Jeffery',
 'James',
 'Carlos',
 'Alec',
 'Amy',
 'Jessica',
 'Felicia',
 'Pamela',
 'Alan',
 'Jessica',
 'Haley',
 'Heather',
 'Cynthia',
 'Rick',
 'Maria',
 'Brittany',
 'Matthew',
 'Shannon',
 'Daniel',
 'Margaret',
 'Lori',
 'Larry',
 'Robert',
 'Donna',
 'James',
 'Mary',
 'Barbara',
 'Patrick',
 'Nicolas',
 'Holly',
 'Patricia',
 'Barbara',
 'Joanna',
 'Stephen',
 'William',
 'Kathleen',
 'Erin',
 'Jasmine',
 'Ricky',
 'Thomas',
 'John',
 'Rodney',
 'Dominique',
 'Kenneth',
 'Michael',
 'Anne',
 'Courtney',
 'Julie',
 'Jake',
 'Michelle',
 'Kristin',
 'Jeffrey',
 'Crystal',
 'Brittany',
 'Susan',
 'Joyce',
 'Brett',
 'Jeremy',
 'Thomas',
 'Sheri',
 'Courtney',
 'Tina',
 'Ricardo',
 'Daniel',
 'Matthew',
 'Michael',
 'Brianna',
 'Joseph',
 'Mackenzie',
 'Sean',
 'Ronald',
 'Amanda',
 'Ryan',
 'Susan',
 'Kenneth',
 'Mary',
 'Duane',
 'Kenneth',
 'Michael',
 'Michael',
 'Jamie',
 'Anna',
 'Penny',
 'Stephanie',
 'Rebecca',
 'Benjamin',
 'Laura',
 'Emma',
 'Amanda',
 'Heather',
 'Jessica',
 'Jessica',
 'Shelly',
 'Eric',
 'Jonathan',
 'Gabrielle',
 'Richard',
 'Ruth',
 'Caitlin',
 'Robert',
 'Daniel']

In [9]:
import numpy as np
import pandas as pd
names

['Mark',
 'Jeremy',
 'Karen',
 'Susan',
 'Steven',
 'Max',
 'Nicholas',
 'Steven',
 'Kimberly',
 'Theodore',
 'Bonnie',
 'Anthony',
 'Rebecca',
 'Andrea',
 'Nicole',
 'Samantha',
 'Mackenzie',
 'Nicholas',
 'Emma',
 'Antonio',
 'Jeffrey',
 'Stephanie',
 'Victoria',
 'Jared',
 'Fernando',
 'Kelsey',
 'Patricia',
 'Julie',
 'Christopher',
 'Brenda',
 'Brittany',
 'Shannon',
 'Steven',
 'Brenda',
 'John',
 'Penny',
 'James',
 'Jeffrey',
 'Jill',
 'John',
 'Eric',
 'Danny',
 'Lori',
 'Tina',
 'Meagan',
 'Patricia',
 'Donna',
 'Regina',
 'Kristi',
 'Rachel',
 'Jeffrey',
 'Scott',
 'Andrea',
 'Linda',
 'Brent',
 'Brian',
 'Kristen',
 'Randy',
 'Alexandra',
 'Tammy',
 'John',
 'James',
 'Donald',
 'Jeffrey',
 'Amanda',
 'Benjamin',
 'Patricia',
 'Caitlin',
 'Dominique',
 'John',
 'Kelly',
 'Jennifer',
 'Kayla',
 'Melissa',
 'Kathy',
 'Gwendolyn',
 'Brian',
 'Faith',
 'Laura',
 'Jean',
 'Meagan',
 'Allison',
 'Tiffany',
 'Teresa',
 'Andrea',
 'Tracy',
 'Roger',
 'Destiny',
 'Jessica',
 'Monica',
 'Aaron',
 'Jeremy',
 'Roy',
 'Gabriel',
 'Christopher',
 'Lisa',
 'Tonya',
 'Gabriel',
 'Diane',
 'Yvonne',
 'Manuel',
 'Jonathan',
 'Chelsea',
 'Robert',
 'Tina',
 'Christopher',
 'Joseph',
 'Diane',
 'Sophia',
 'Bruce',
 'Anne',
 'Sara',
 'William',
 'Sharon',
 'Karen',
 'Anita',
 'Danielle',
 'John',
 'Tammy',
 'Sarah',
 'Deanna',
 'Kaitlyn',
 'Laura',
 'David',
 'Gina',
 'Maxwell',
 'Jeffrey',
 'Kathleen',
 'Debbie',
 'Shawn',
 'Sara',
 'Erika',
 'John',
 'Molly',
 'Karen',
 'Jay',
 'Kelli',
 'Joseph',
 'Carol',
 'Nicholas',
 'Robert',
 'Tina',
 'Olivia',
 'Matthew',
 'Robert',
 'Matthew',
 'Evan',
 'Anthony',
 'Christina',
 'Lauren',
 'Alexander',
 'Joseph',
 'Morgan',
 'Meghan',
 'Monica',
 'Aaron',
 'Cathy',
 'Dennis',
 'Brittany',
 'Gregory',
 'Peter',
 'Daniel',
 'Monica',
 'Darrell',
 'Albert',
 'Tammy',
 'Kelsey',
 'Christie',
 'Erin',
 'Cameron',
 'Jeffrey',
 'Megan',
 'Shawn',
 'Kelsey',
 'Jill',
 'Samuel',
 'William',
 'Ricardo',
 'Michael',
 'Stephen',
 'Brittany',
 'Ashley',
 'Christopher',
 'Andrew',
 'Patricia',
 'Kimberly',
 'Christopher',
 'Steven',
 'Gina',
 'Sean',
 'David',
 'Brittney',
 'Margaret',
 'Rebecca',
 'Theresa',
 'Ashley',
 'Anthony',
 'Eric',
 'Denise',
 'Claudia',
 'Anthony',
 'Charles',
 'Kelly',
 'Robert',
 'Jessica',
 'Joseph',
 'Angela',
 'Andrea',
 'Deborah',
 'David',
 'Jesse',
 'Melanie',
 'Brandon',
 'Terrence',
 'Melissa',
 'Patricia',
 'Eric',
 'Regina',
 'Kristen',
 'Paul',
 'Kathryn',
 'Jennifer',
 'Steven',
 'Lauren',
 'Samuel',
 'Janet',
 'Emily',
 'Brandon',
 'Michael',
 'Tim',
 'Kimberly',
 'Regina',
 'Michael',
 'Jonathan',
 'Laura',
 'Kristi',
 'Michael',
 'Riley',
 'Albert',
 'Amanda',
 'Christina',
 'Joseph',
 'Maria',
 'Samantha',
 'Glenda',
 'Amy',
 'Frances',
 'Jesus',
 'Joseph',
 'Jennifer',
 'Stephanie',
 'Stephen',
 'Larry',
 'Kevin',
 'Cheryl',
 'Karen',
 'Mary',
 'Janet',
 'Jeffrey',
 'Sophia',
 'Stephanie',
 'Amanda',
 'Jeffrey',
 'Kevin',
 'Brittany',
 'Craig',
 'Wendy',
 'Johnny',
 'James',
 'Jeffrey',
 'Peggy',
 'Jessica',
 'Dominique',
 'Kevin',
 'Rachel',
 'Ashley',
 'Jasmine',
 'Linda',
 'Scott',
 'Anthony',
 'Daniel',
 'Donna',
 'Jennifer',
 'Crystal',
 'Michael',
 'Stephanie',
 'Jason',
 'Gina',
 'Sabrina',
 'Dawn',
 'Bruce',
 'Ricky',
 'Julie',
 'Crystal',
 'Eric',
 'Sarah',
 'Michelle',
 'Amanda',
 'Bailey',
 'Antonio',
 'Brianna',
 'James',
 'Michael',
 'Veronica',
 'Michael',
 'Angela',
 'Allen',
 'Jennifer',
 'Donna',
 'Daniel',
 'Rhonda',
 'Travis',
 'Lisa',
 'Corey',
 'Gabriel',
 'Jessica',
 'Amanda',
 'John',
 'Howard',
 'Melissa',
 'Tony',
 'Elizabeth',
 'Dominique',
 'Sara',
 'Mark',
 'Marcus',
 'John',
 'Paul',
 'Stacey',
 'Samantha',
 'Debbie',
 'William',
 'Jeffery',
 'Kayla',
 'Kim',
 'Wayne',
 'Christopher',
 'Samantha',
 'Melissa',
 'William',
 'Stacy',
 'Chelsea',
 'Jason',
 'Jennifer',
 'Renee',
 'Peter',
 'Douglas',
 'Nicholas',
 'Michael',
 'Jacob',
 'Craig',
 'Anthony',
 'Vickie',
 'Jessica',
 'Gina',
 'Jay',
 'Brandi',
 'Kendra',
 'Charles',
 'Rachel',
 'Brian',
 'Scott',
 'Alisha',
 'Brianna',
 'Kim',
 'Antonio',
 'Henry',
 'Helen',
 'Christina',
 'Leslie',
 'Wendy',
 'David',
 'Kayla',
 'Mary',
 'Charlene',
 'Christine',
 'Christopher',
 'Meghan',
 'Harry',
 'Amy',
 'Brandy',
 'Tina',
 'Jonathan',
 'Alex',
 'Kristen',
 'Sandy',
 'Lisa',
 'Faith',
 'Christian',
 'Debra',
 'Monica',
 'Donald',
 'Courtney',
 'Tanya',
 'Brooke',
 'Deanna',
 'Christopher',
 'Anthony',
 'Miguel',
 'Jeffery',
 'James',
 'Carlos',
 'Alec',
 'Amy',
 'Jessica',
 'Felicia',
 'Pamela',
 'Alan',
 'Jessica',
 'Haley',
 'Heather',
 'Cynthia',
 'Rick',
 'Maria',
 'Brittany',
 'Matthew',
 'Shannon',
 'Daniel',
 'Margaret',
 'Lori',
 'Larry',
 'Robert',
 'Donna',
 'James',
 'Mary',
 'Barbara',
 'Patrick',
 'Nicolas',
 'Holly',
 'Patricia',
 'Barbara',
 'Joanna',
 'Stephen',
 'William',
 'Kathleen',
 'Erin',
 'Jasmine',
 'Ricky',
 'Thomas',
 'John',
 'Rodney',
 'Dominique',
 'Kenneth',
 'Michael',
 'Anne',
 'Courtney',
 'Julie',
 'Jake',
 'Michelle',
 'Kristin',
 'Jeffrey',
 'Crystal',
 'Brittany',
 'Susan',
 'Joyce',
 'Brett',
 'Jeremy',
 'Thomas',
 'Sheri',
 'Courtney',
 'Tina',
 'Ricardo',
 'Daniel',
 'Matthew',
 'Michael',
 'Brianna',
 'Joseph',
 'Mackenzie',
 'Sean',
 'Ronald',
 'Amanda',
 'Ryan',
 'Susan',
 'Kenneth',
 'Mary',
 'Duane',
 'Kenneth',
 'Michael',
 'Michael',
 'Jamie',
 'Anna',
 'Penny',
 'Stephanie',
 'Rebecca',
 'Benjamin',
 'Laura',
 'Emma',
 'Amanda',
 'Heather',
 'Jessica',
 'Jessica',
 'Shelly',
 'Eric',
 'Jonathan',
 'Gabrielle',
 'Richard',
 'Ruth',
 'Caitlin',
 'Robert',
 'Daniel']

In [10]:
names.sort()

In [11]:
names

['Aaron',
 'Aaron',
 'Alan',
 'Albert',
 'Albert',
 'Alec',
 'Alex',
 'Alexander',
 'Alexandra',
 'Alisha',
 'Allen',
 'Allison',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amanda',
 'Amy',
 'Amy',
 'Amy',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrea',
 'Andrew',
 'Angela',
 'Angela',
 'Anita',
 'Anna',
 'Anne',
 'Anne',
 'Anthony',
 'Anthony',
 'Anthony',
 'Anthony',
 'Anthony',
 'Anthony',
 'Anthony',
 'Antonio',
 'Antonio',
 'Antonio',
 'Ashley',
 'Ashley',
 'Ashley',
 'Bailey',
 'Barbara',
 'Barbara',
 'Benjamin',
 'Benjamin',
 'Bonnie',
 'Brandi',
 'Brandon',
 'Brandon',
 'Brandy',
 'Brenda',
 'Brenda',
 'Brent',
 'Brett',
 'Brian',
 'Brian',
 'Brian',
 'Brianna',
 'Brianna',
 'Brianna',
 'Brittany',
 'Brittany',
 'Brittany',
 'Brittany',
 'Brittany',
 'Brittany',
 'Brittney',
 'Brooke',
 'Bruce',
 'Bruce',
 'Caitlin',
 'Caitlin',
 'Cameron',
 'Carlos',
 'Carol',
 'Cathy',
 'Charlene',
 'Charles',
 'Charles',
 'Chelsea',
 'Chelsea',
 'Cheryl',
 'Christian',
 'Christie',
 'Christina',
 'Christina',
 'Christina',
 'Christine',
 'Christopher',
 'Christopher',
 'Christopher',
 'Christopher',
 'Christopher',
 'Christopher',
 'Christopher',
 'Christopher',
 'Claudia',
 'Corey',
 'Courtney',
 'Courtney',
 'Courtney',
 'Craig',
 'Craig',
 'Crystal',
 'Crystal',
 'Crystal',
 'Cynthia',
 'Daniel',
 'Daniel',
 'Daniel',
 'Daniel',
 'Daniel',
 'Daniel',
 'Danielle',
 'Danny',
 'Darrell',
 'David',
 'David',
 'David',
 'David',
 'Dawn',
 'Deanna',
 'Deanna',
 'Debbie',
 'Debbie',
 'Deborah',
 'Debra',
 'Denise',
 'Dennis',
 'Destiny',
 'Diane',
 'Diane',
 'Dominique',
 'Dominique',
 'Dominique',
 'Dominique',
 'Donald',
 'Donald',
 'Donna',
 'Donna',
 'Donna',
 'Donna',
 'Douglas',
 'Duane',
 'Elizabeth',
 'Emily',
 'Emma',
 'Emma',
 'Eric',
 'Eric',
 'Eric',
 'Eric',
 'Eric',
 'Erika',
 'Erin',
 'Erin',
 'Evan',
 'Faith',
 'Faith',
 'Felicia',
 'Fernando',
 'Frances',
 'Gabriel',
 'Gabriel',
 'Gabriel',
 'Gabrielle',
 'Gina',
 'Gina',
 'Gina',
 'Gina',
 'Glenda',
 'Gregory',
 'Gwendolyn',
 'Haley',
 'Harry',
 'Heather',
 'Heather',
 'Helen',
 'Henry',
 'Holly',
 'Howard',
 'Jacob',
 'Jake',
 'James',
 'James',
 'James',
 'James',
 'James',
 'James',
 'Jamie',
 'Janet',
 'Janet',
 'Jared',
 'Jasmine',
 'Jasmine',
 'Jason',
 'Jason',
 'Jay',
 'Jay',
 'Jean',
 'Jeffery',
 'Jeffery',
 'Jeffrey',
 'Jeffrey',
 'Jeffrey',
 'Jeffrey',
 'Jeffrey',
 'Jeffrey',
 'Jeffrey',
 'Jeffrey',
 'Jeffrey',
 'Jeffrey',
 'Jennifer',
 'Jennifer',
 'Jennifer',
 'Jennifer',
 'Jennifer',
 'Jennifer',
 'Jeremy',
 'Jeremy',
 'Jeremy',
 'Jesse',
 'Jessica',
 'Jessica',
 'Jessica',
 'Jessica',
 'Jessica',
 'Jessica',
 'Jessica',
 'Jessica',
 'Jessica',
 'Jesus',
 'Jill',
 'Jill',
 'Joanna',
 'John',
 'John',
 'John',
 'John',
 'John',
 'John',
 'John',
 'John',
 'John',
 'Johnny',
 'Jonathan',
 'Jonathan',
 'Jonathan',
 'Jonathan',
 'Joseph',
 'Joseph',
 'Joseph',
 'Joseph',
 'Joseph',
 'Joseph',
 'Joseph',
 'Joyce',
 'Julie',
 'Julie',
 'Julie',
 'Kaitlyn',
 'Karen',
 'Karen',
 'Karen',
 'Karen',
 'Kathleen',
 'Kathleen',
 'Kathryn',
 'Kathy',
 'Kayla',
 'Kayla',
 'Kayla',
 'Kelli',
 'Kelly',
 'Kelly',
 'Kelsey',
 'Kelsey',
 'Kelsey',
 'Kendra',
 'Kenneth',
 'Kenneth',
 'Kenneth',
 'Kevin',
 'Kevin',
 'Kevin',
 'Kim',
 'Kim',
 'Kimberly',
 'Kimberly',
 'Kimberly',
 'Kristen',
 'Kristen',
 'Kristen',
 'Kristi',
 'Kristi',
 'Kristin',
 'Larry',
 'Larry',
 'Laura',
 'Laura',
 'Laura',
 'Laura',
 'Lauren',
 'Lauren',
 'Leslie',
 'Linda',
 'Linda',
 'Lisa',
 'Lisa',
 'Lisa',
 'Lori',
 'Lori',
 'Mackenzie',
 'Mackenzie',
 'Manuel',
 'Marcus',
 'Margaret',
 'Margaret',
 'Maria',
 'Maria',
 'Mark',
 'Mark',
 'Mary',
 'Mary',
 'Mary',
 'Mary',
 'Matthew',
 'Matthew',
 'Matthew',
 'Matthew',
 'Max',
 'Maxwell',
 'Meagan',
 'Meagan',
 'Megan',
 'Meghan',
 'Meghan',
 'Melanie',
 'Melissa',
 'Melissa',
 'Melissa',
 'Melissa',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michael',
 'Michelle',
 'Michelle',
 'Miguel',
 'Molly',
 'Monica',
 'Monica',
 'Monica',
 'Monica',
 'Morgan',
 'Nicholas',
 'Nicholas',
 'Nicholas',
 'Nicholas',
 'Nicolas',
 'Nicole',
 'Olivia',
 'Pamela',
 'Patricia',
 'Patricia',
 'Patricia',
 'Patricia',
 'Patricia',
 'Patricia',
 'Patrick',
 'Paul',
 'Paul',
 'Peggy',
 'Penny',
 'Penny',
 'Peter',
 'Peter',
 'Rachel',
 'Rachel',
 'Rachel',
 'Randy',
 'Rebecca',
 'Rebecca',
 'Rebecca',
 'Regina',
 'Regina',
 'Regina',
 'Renee',
 'Rhonda',
 'Ricardo',
 'Ricardo',
 'Richard',
 'Rick',
 'Ricky',
 'Ricky',
 'Riley',
 'Robert',
 'Robert',
 'Robert',
 'Robert',
 'Robert',
 'Robert',
 'Rodney',
 'Roger',
 'Ronald',
 'Roy',
 'Ruth',
 'Ryan',
 'Sabrina',
 'Samantha',
 'Samantha',
 'Samantha',
 'Samantha',
 'Samuel',
 'Samuel',
 'Sandy',
 'Sara',
 'Sara',
 'Sara',
 'Sarah',
 'Sarah',
 'Scott',
 'Scott',
 'Scott',
 'Sean',
 'Sean',
 'Shannon',
 'Shannon',
 'Sharon',
 'Shawn',
 'Shawn',
 'Shelly',
 'Sheri',
 'Sophia',
 'Sophia',
 'Stacey',
 'Stacy',
 'Stephanie',
 'Stephanie',
 'Stephanie',
 'Stephanie',
 'Stephanie',
 'Stephen',
 'Stephen',
 'Stephen',
 'Steven',
 'Steven',
 'Steven',
 'Steven',
 'Steven',
 'Susan',
 'Susan',
 'Susan',
 'Tammy',
 'Tammy',
 'Tammy',
 'Tanya',
 'Teresa',
 'Terrence',
 'Theodore',
 'Theresa',
 'Thomas',
 'Thomas',
 'Tiffany',
 'Tim',
 'Tina',
 'Tina',
 'Tina',
 'Tina',
 'Tina',
 'Tony',
 'Tonya',
 'Tracy',
 'Travis',
 'Veronica',
 'Vickie',
 'Victoria',
 'Wayne',
 'Wendy',
 'Wendy',
 'William',
 'William',
 'William',
 'William',
 'William',
 'Yvonne']

In [12]:
roll_numbers = np.arange(2026001, 2026001 + 500)

In [13]:
roll_numbers

array([2026001, 2026002, 2026003, 2026004, 2026005, 2026006, 2026007,
       2026008, 2026009, 2026010, 2026011, 2026012, 2026013, 2026014,
       2026015, 2026016, 2026017, 2026018, 2026019, 2026020, 2026021,
       2026022, 2026023, 2026024, 2026025, 2026026, 2026027, 2026028,
       2026029, 2026030, 2026031, 2026032, 2026033, 2026034, 2026035,
       2026036, 2026037, 2026038, 2026039, 2026040, 2026041, 2026042,
       2026043, 2026044, 2026045, 2026046, 2026047, 2026048, 2026049,
       2026050, 2026051, 2026052, 2026053, 2026054, 2026055, 2026056,
       2026057, 2026058, 2026059, 2026060, 2026061, 2026062, 2026063,
       2026064, 2026065, 2026066, 2026067, 2026068, 2026069, 2026070,
       2026071, 2026072, 2026073, 2026074, 2026075, 2026076, 2026077,
       2026078, 2026079, 2026080, 2026081, 2026082, 2026083, 2026084,
       2026085, 2026086, 2026087, 2026088, 2026089, 2026090, 2026091,
       2026092, 2026093, 2026094, 2026095, 2026096, 2026097, 2026098,
       2026099, 2026100, 2026101, 2026102, 2026103, 2026104, 2026105,
       2026106, 2026107, 2026108, 2026109, 2026110, 2026111, 2026112,
       2026113, 2026114, 2026115, 2026116, 2026117, 2026118, 2026119,
       2026120, 2026121, 2026122, 2026123, 2026124, 2026125, 2026126,
       2026127, 2026128, 2026129, 2026130, 2026131, 2026132, 2026133,
       2026134, 2026135, 2026136, 2026137, 2026138, 2026139, 2026140,
       2026141, 2026142, 2026143, 2026144, 2026145, 2026146, 2026147,
       2026148, 2026149, 2026150, 2026151, 2026152, 2026153, 2026154,
       2026155, 2026156, 2026157, 2026158, 2026159, 2026160, 2026161,
       2026162, 2026163, 2026164, 2026165, 2026166, 2026167, 2026168,
       2026169, 2026170, 2026171, 2026172, 2026173, 2026174, 2026175,
       2026176, 2026177, 2026178, 2026179, 2026180, 2026181, 2026182,
       2026183, 2026184, 2026185, 2026186, 2026187, 2026188, 2026189,
       2026190, 2026191, 2026192, 2026193, 2026194, 2026195, 2026196,
       2026197, 2026198, 2026199, 2026200, 2026201, 2026202, 2026203,
       2026204, 2026205, 2026206, 2026207, 2026208, 2026209, 2026210,
       2026211, 2026212, 2026213, 2026214, 2026215, 2026216, 2026217,
       2026218, 2026219, 2026220, 2026221, 2026222, 2026223, 2026224,
       2026225, 2026226, 2026227, 2026228, 2026229, 2026230, 2026231,
       2026232, 2026233, 2026234, 2026235, 2026236, 2026237, 2026238,
       2026239, 2026240, 2026241, 2026242, 2026243, 2026244, 2026245,
       2026246, 2026247, 2026248, 2026249, 2026250, 2026251, 2026252,
       2026253, 2026254, 2026255, 2026256, 2026257, 2026258, 2026259,
       2026260, 2026261, 2026262, 2026263, 2026264, 2026265, 2026266,
       2026267, 2026268, 2026269, 2026270, 2026271, 2026272, 2026273,
       2026274, 2026275, 2026276, 2026277, 2026278, 2026279, 2026280,
       2026281, 2026282, 2026283, 2026284, 2026285, 2026286, 2026287,
       2026288, 2026289, 2026290, 2026291, 2026292, 2026293, 2026294,
       2026295, 2026296, 2026297, 2026298, 2026299, 2026300, 2026301,
       2026302, 2026303, 2026304, 2026305, 2026306, 2026307, 2026308,
       2026309, 2026310, 2026311, 2026312, 2026313, 2026314, 2026315,
       2026316, 2026317, 2026318, 2026319, 2026320, 2026321, 2026322,
       2026323, 2026324, 2026325, 2026326, 2026327, 2026328, 2026329,
       2026330, 2026331, 2026332, 2026333, 2026334, 2026335, 2026336,
       2026337, 2026338, 2026339, 2026340, 2026341, 2026342, 2026343,
       2026344, 2026345, 2026346, 2026347, 2026348, 2026349, 2026350,
       2026351, 2026352, 2026353, 2026354, 2026355, 2026356, 2026357,
       2026358, 2026359, 2026360, 2026361, 2026362, 2026363, 2026364,
       2026365, 2026366, 2026367, 2026368, 2026369, 2026370, 2026371,
       2026372, 2026373, 2026374, 2026375, 2026376, 2026377, 2026378,
       2026379, 2026380, 2026381, 2026382, 2026383, 2026384, 2026385,
       2026386, 2026387, 2026388, 2026389, 2026390, 2026391, 2026392,
       2026393, 2026394, 2026395, 2026396, 2026397, 2026398, 2026399,
       2026400, 2026401, 2026402, 2026403, 2026404, 2026405, 2026406,
       2026407, 2026408, 2026409, 2026410, 2026411, 2026412, 2026413,
       2026414, 2026415, 2026416, 2026417, 2026418, 2026419, 2026420,
       2026421, 2026422, 2026423, 2026424, 2026425, 2026426, 2026427,
       2026428, 2026429, 2026430, 2026431, 2026432, 2026433, 2026434,
       2026435, 2026436, 2026437, 2026438, 2026439, 2026440, 2026441,
       2026442, 2026443, 2026444, 2026445, 2026446, 2026447, 2026448,
       2026449, 2026450, 2026451, 2026452, 2026453, 2026454, 2026455,
       2026456, 2026457, 2026458, 2026459, 2026460, 2026461, 2026462,
       2026463, 2026464, 2026465, 2026466, 2026467, 2026468, 2026469,
       2026470, 2026471, 2026472, 2026473, 2026474, 2026475, 2026476,
       2026477, 2026478, 2026479, 2026480, 2026481, 2026482, 2026483,
       2026484, 2026485, 2026486, 2026487, 2026488, 2026489, 2026490,
       2026491, 2026492, 2026493, 2026494, 2026495, 2026496, 2026497,
       2026498, 2026499, 2026500])

In [14]:
df = pd.DataFrame({
    "Names":names,
    "Roll_no":roll_numbers
})
df

       Names  Roll_no
0      Aaron  2026001
1      Aaron  2026002
2       Alan  2026003
3     Albert  2026004
4     Albert  2026005
..       ...      ...
495  William  2026496
496  William  2026497
497  William  2026498
498  William  2026499
499   Yvonne  2026500

[500 rows x 2 columns]

In [15]:
np.random.seed(0)
df[["Maths"]] = np.random.randint(25,101,size = (500,1))
df[["Science"]] = np.random.randint(25,101,size = (500,1))
df[["Social_sci"]] = np.random.randint(25,101,size = (500,1))
df[["Marathi"]] = np.random.randint(25,101,size = (500,1))
df[["Kannada"]] = np.random.randint(25,101,size = (500,1))
df[["English"]] = np.random.randint(25,101,size = (500,1))

In [16]:
df

       Names  Roll_no  Maths  Science  Social_sci  Marathi  Kannada  English
0      Aaron  2026001     69       50          54       81       88       76
1      Aaron  2026002     72       46          52       34       90       42
2       Alan  2026003     89       70          28       91       46       28
3     Albert  2026004     92       41          58       34       71       33
4     Albert  2026005     92       50          76       61       25       72
..       ...      ...    ...      ...         ...      ...      ...      ...
495  William  2026496     79       39          95       73       89       48
496  William  2026497     46       54          31       85       33       30
497  William  2026498     56       76          73       31       92       86
498  William  2026499     60       85          34       95       31       27
499   Yvonne  2026500     33       92          53       26       32       25

[500 rows x 8 columns]

In [18]:
df

       Names  Roll_no  Maths  Science  Social_sci  Marathi  Kannada  English
0      Aaron  2026001     69       50          54       81       88       76
1      Aaron  2026002     72       46          52       34       90       42
2       Alan  2026003     89       70          28       91       46       28
3     Albert  2026004     92       41          58       34       71       33
4     Albert  2026005     92       50          76       61       25       72
..       ...      ...    ...      ...         ...      ...      ...      ...
495  William  2026496     79       39          95       73       89       48
496  William  2026497     46       54          31       85       33       30
497  William  2026498     56       76          73       31       92       86
498  William  2026499     60       85          34       95       31       27
499   Yvonne  2026500     33       92          53       26       32       25

[500 rows x 8 columns]

In [19]:
df.info

<bound method DataFrame.info of        Names  Roll_no  Maths  Science  Social_sci  Marathi  Kannada  English
0      Aaron  2026001     69       50          54       81       88       76
1      Aaron  2026002     72       46          52       34       90       42
2       Alan  2026003     89       70          28       91       46       28
3     Albert  2026004     92       41          58       34       71       33
4     Albert  2026005     92       50          76       61       25       72
..       ...      ...    ...      ...         ...      ...      ...      ...
495  William  2026496     79       39          95       73       89       48
496  William  2026497     46       54          31       85       33       30
497  William  2026498     56       76          73       31       92       86
498  William  2026499     60       85          34       95       31       27
499   Yvonne  2026500     33       92          53       26       32       25

[500 rows x 8 columns]>

In [20]:
df

       Names  Roll_no  Maths  Science  Social_sci  Marathi  Kannada  English
0      Aaron  2026001     69       50          54       81       88       76
1      Aaron  2026002     72       46          52       34       90       42
2       Alan  2026003     89       70          28       91       46       28
3     Albert  2026004     92       41          58       34       71       33
4     Albert  2026005     92       50          76       61       25       72
..       ...      ...    ...      ...         ...      ...      ...      ...
495  William  2026496     79       39          95       73       89       48
496  William  2026497     46       54          31       85       33       30
497  William  2026498     56       76          73       31       92       86
498  William  2026499     60       85          34       95       31       27
499   Yvonne  2026500     33       92          53       26       32       25

[500 rows x 8 columns]

In [22]:
df

       Names  Roll_no  Maths  Science  Social_sci  Marathi  Kannada  English
0      Aaron  2026001     69       50          54       81       88       76
1      Aaron  2026002     72       46          52       34       90       42
2       Alan  2026003     89       70          28       91       46       28
3     Albert  2026004     92       41          58       34       71       33
4     Albert  2026005     92       50          76       61       25       72
..       ...      ...    ...      ...         ...      ...      ...      ...
495  William  2026496     79       39          95       73       89       48
496  William  2026497     46       54          31       85       33       30
497  William  2026498     56       76          73       31       92       86
498  William  2026499     60       85          34       95       31       27
499   Yvonne  2026500     33       92          53       26       32       25

[500 rows x 8 columns]

In [23]:
np.random.seed(0)
marks = np.random.randint(25,101,size = (500,6))
marks

array([[69, 72, 89, 92, 92, 34],
       [46, 61, 95, 37, 83, 90],
       [64, 71, 62, 50, 97, 34],
       ...,
       [28, 32, 29, 29, 78, 34],
       [93, 58, 74, 99, 48, 82],
       [46, 48, 30, 86, 27, 25]], shape=(500, 6), dtype=int32)

In [24]:
dataframe = pd.DataFrame(marks,
                        #rows = names,
                        columns = ["Maths","Science","Social_sci","Marathi","Kannada","English"])

In [25]:
dataframe

     Maths  Science  Social_sci  Marathi  Kannada  English
0       69       72          89       92       92       34
1       46       61          95       37       83       90
2       64       71          62       50       97       34
3       45       94          72       89       74       54
4       44       44          39       64       57       90
..     ...      ...         ...      ...      ...      ...
495     59       65          75       87       68       63
496     44       67          46       45       60       52
497     28       32          29       29       78       34
498     93       58          74       99       48       82
499     46       48          30       86       27       25

[500 rows x 6 columns]

In [26]:
dataframe["Names"] = names
dataframe["Roll_No"] = roll_numbers

In [27]:
dataframe

     Maths  Science  Social_sci  Marathi  Kannada  English    Names  Roll_No
0       69       72          89       92       92       34    Aaron  2026001
1       46       61          95       37       83       90    Aaron  2026002
2       64       71          62       50       97       34     Alan  2026003
3       45       94          72       89       74       54   Albert  2026004
4       44       44          39       64       57       90   Albert  2026005
..     ...      ...         ...      ...      ...      ...      ...      ...
495     59       65          75       87       68       63  William  2026496
496     44       67          46       45       60       52  William  2026497
497     28       32          29       29       78       34  William  2026498
498     93       58          74       99       48       82  William  2026499
499     46       48          30       86       27       25   Yvonne  2026500

[500 rows x 8 columns]

In [30]:
dataframe.columns

Index(['Maths', 'Science', 'Social_sci', 'Marathi', 'Kannada', 'English',
       'Names', 'Roll_No'],
      dtype='str')

In [33]:
dataframe = dataframe[[
    "Roll_No",
    "Names",
    "Maths",
    "Science",
    "Social_sci",
    "English",
    "Marathi",
    "Kannada"
]]

In [34]:
dataframe

     Roll_No    Names  Maths  Science  Social_sci  English  Marathi  Kannada
0    2026001    Aaron     69       72          89       34       92       92
1    2026002    Aaron     46       61          95       90       37       83
2    2026003     Alan     64       71          62       34       50       97
3    2026004   Albert     45       94          72       54       89       74
4    2026005   Albert     44       44          39       90       64       57
..       ...      ...    ...      ...         ...      ...      ...      ...
495  2026496  William     59       65          75       63       87       68
496  2026497  William     44       67          46       52       45       60
497  2026498  William     28       32          29       34       29       78
498  2026499  William     93       58          74       82       99       48
499  2026500   Yvonne     46       48          30       25       86       27

[500 rows x 8 columns]

In [36]:
dataframe.dtypes

Roll_No       int64
Names           str
Maths         int32
Science       int32
Social_sci    int32
English       int32
Marathi       int32
Kannada       int32
dtype: object

<h3>Calculating sum in columns and rows</h3><br>
axis=0  # column-wise<br>
axis=1  # row-wise

<h2>example</h2>
df["Total"] = df[subjects].sum(axis=1)

output:
        85 + 90 + 78 + 88 + 92 + 75

In [37]:
# Calculating the total marks 
subjects =[
    "Maths",
    "Science",
    "Social_sci",
    "English",
    "Marathi",
    "Kannada"
]

dataframe["Total_marks"] = dataframe[subjects].sum(axis=1)
dataframe

,Roll_No,Names,Maths,Science,Social_sci,English,Marathi,Kannada,Total_marks
0,2026001,Aaron,69,72,89,34,92,92,448
1,2026002,Aaron,46,61,95,90,37,83,412
2,2026003,Alan,64,71,62,34,50,97,378
3,2026004,Albert,45,94,72,54,89,74,428
4,2026005,Albert,44,44,39,90,64,57,338
...,...,...,...,...,...,...,...,...,...
495,2026496,William,59,65,75,63,87,68,417
496,2026497,William,44,67,46,52,45,60,314
497,2026498,William,28,32,29,34,29,78,230
498,2026499,William,93,58,74,82,99,48,454
499,2026500,Yvonne,46,48,30,25,86,27,262

In [96]:
# Calculating the % of the students
dataframe["Percentage"] = (dataframe["Total_marks"]/600)*100
dataframe

,Roll_No,Names,Maths,Science,Social_sci,English,Marathi,Kannada,Total_marks,Percentage,Result,Failed_subjects,Grade
0,2026001,Aaron,69,72,89,34,92,92,448,74.666667,Fail,English,F
1,2026002,Aaron,46,61,95,90,37,83,412,68.666667,Pass,None,B
2,2026003,Alan,64,71,62,34,50,97,378,63.000000,Fail,English,F
3,2026004,Albert,45,94,72,54,89,74,428,71.333333,Pass,None,B+
4,2026005,Albert,44,44,39,90,64,57,338,56.333333,Pass,None,C+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2026496,William,59,65,75,63,87,68,417,69.500000,Pass,None,B
496,2026497,William,44,67,46,52,45,60,314,52.333333,Pass,None,C+
497,2026498,William,28,32,29,34,29,78,230,38.333333,Fail,"Maths, Science, Social_sci, English, Marathi",F
498,2026499,William,93,58,74,82,99,48,454,75.666667,Pass,None,B+
499,2026500,Yvonne,46,48,30,25,86,27,262,43.666667,Fail,"Social_sci, English, Kannada",F

Now lets calculate weather student is pass or fail.<br>
<b>conditions</b><br>
student should get above 35 marks in all the subject. then student is pass, otherwise he fails.<br>

In [49]:
def check_result(row):
    failed_subjects=[]

    for subject in subjects:

        if row[subject] < 35:
            failed_subjects.append(subject)
    if len(failed_subjects) == 0:
        return pd.Series(["Pass","None"])

    else:
        return pd.Series([
            "Fail",
            ", ".join(failed_subjects)
        ])
dataframe[["Result", "Failed_subjects"]] = dataframe.apply(
        check_result,
        axis = 1
    )

dataframe

,Roll_No,Names,Maths,Science,Social_sci,English,Marathi,Kannada,Total_marks,Percentage,Result,Failed_subjects
0,2026001,Aaron,69,72,89,34,92,92,448,74.666667,Fail,English
1,2026002,Aaron,46,61,95,90,37,83,412,68.666667,Pass,None
2,2026003,Alan,64,71,62,34,50,97,378,63.000000,Fail,English
3,2026004,Albert,45,94,72,54,89,74,428,71.333333,Pass,None
4,2026005,Albert,44,44,39,90,64,57,338,56.333333,Pass,None
...,...,...,...,...,...,...,...,...,...,...,...,...
495,2026496,William,59,65,75,63,87,68,417,69.500000,Pass,None
496,2026497,William,44,67,46,52,45,60,314,52.333333,Pass,None
497,2026498,William,28,32,29,34,29,78,230,38.333333,Fail,"Maths, Science, Social_sci, English, Marathi"
498,2026499,William,93,58,74,82,99,48,454,75.666667,Pass,None
499,2026500,Yvonne,46,48,30,25,86,27,262,43.666667,Fail,"Social_sci, English, Kannada"

<h3>Grade calculation</h3>

<h4>Important Condition</h4>
<p>A student should get a grade only if they pass all subjects.<br>

<b>Rules</b><br>
If the student fails in any one subject → Grade = F<br>
<b>Otherwise:</b><br>
Percentage ≥ 90 → A+<br>
Percentage ≥ 80 → A<br>
Percentage ≥ 70 → B<br>
Percentage ≥ 60 → C<br>
Percentage ≥ 50 → D<br>
Percentage ≥ 35 → E
</p>

In [60]:
def check_grade(row):
    if row["Result"] == "Fail":
        return "F"
    else:
        if row["Percentage"] >= 90:
            return "A+"
        elif row["Percentage"] >= 80:
            return "A"
        elif row["Percentage"] >= 70:
            return "B+"
        elif row["Percentage"] >= 60:
            return "B"
        elif row["Percentage"] >= 50:
            return "C+"
        else:
            return "C"

dataframe["Grade"] = dataframe.apply(
    check_grade,
    axis = 1
)

dataframe

,Roll_No,Names,Maths,Science,Social_sci,English,Marathi,Kannada,Total_marks,Percentage,Result,Failed_subjects,Grade
0,2026001,Aaron,69,72,89,34,92,92,448,74.666667,Fail,English,F
1,2026002,Aaron,46,61,95,90,37,83,412,68.666667,Pass,None,B
2,2026003,Alan,64,71,62,34,50,97,378,63.000000,Fail,English,F
3,2026004,Albert,45,94,72,54,89,74,428,71.333333,Pass,None,B+
4,2026005,Albert,44,44,39,90,64,57,338,56.333333,Pass,None,C+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2026496,William,59,65,75,63,87,68,417,69.500000,Pass,None,B
496,2026497,William,44,67,46,52,45,60,314,52.333333,Pass,None,C+
497,2026498,William,28,32,29,34,29,78,230,38.333333,Fail,"Maths, Science, Social_sci, English, Marathi",F
498,2026499,William,93,58,74,82,99,48,454,75.666667,Pass,None,B+
499,2026500,Yvonne,46,48,30,25,86,27,262,43.666667,Fail,"Social_sci, English, Kannada",F

<b>Toppers of the class</b>

In [70]:
def toppers_of_class():
    passed_students = dataframe[
        dataframe["Result"] == "Pass"
    ]
    top_10 = passed_students.sort_values(
        by = "Total_marks",
        ascending = False
    ).head(10)
    return top_10

top_10 = toppers_of_class()
top_10

,Roll_No,Names,Maths,Science,Social_sci,English,Marathi,Kannada,Total_marks,Percentage,Result,Failed_subjects,Grade
85,2026086,Chelsea,99,79,87,70,97,96,528,88.000000,Pass,None,A
472,2026473,Terrence,79,90,97,74,83,98,521,86.833333,Pass,None,A
290,2026291,Kevin,72,73,96,87,92,96,516,86.000000,Pass,None,A
183,2026184,Helen,93,97,58,90,73,94,505,84.166667,Pass,None,A
424,2026425,Samantha,90,76,86,65,94,83,494,82.333333,Pass,None,A
66,2026067,Brittany,93,51,76,94,98,78,490,81.666667,Pass,None,A
112,2026113,Cynthia,86,92,41,87,98,81,485,80.833333,Pass,None,A
351,2026352,Michael,83,100,82,97,83,38,483,80.500000,Pass,None,A
199,2026200,Jasmine,93,81,57,56,97,98,482,80.333333,Pass,None,A
493,2026494,Wendy,94,86,64,100,84,52,480,80.000000,Pass,None,A

In [86]:
Passed_students = dataframe[
        dataframe["Result"] == "Pass"
    ]
Failed_students = dataframe[
        dataframe["Result"] == "Fail"
    ]
No_of_students_passed = len(Passed_students)
No_of_students_failed = len(Failed_students)

Passed_percentage = No_of_students_passed/500*100
Failed_percentage = No_of_students_failed/500*100

In [91]:
No_of_students_passed ,Passed_percentage

(204, 40.8)

In [92]:
No_of_students_failed , Failed_percentage

(296, 59.199999999999996)

<h3>Subject Analysis</h3><br>

In [97]:
def subject_analysis(dataframe, subject):

    total_students = len(dataframe)

    topper = dataframe.loc[
        dataframe[subject].idxmax()
    ]

    passed = (
        dataframe[subject] >= 35
    ).sum()

    failed = (
        dataframe[subject] < 35
    ).sum()

    pass_percentage = (
        passed / total_students
    ) * 100

    fail_percentage = (
        failed / total_students
    ) * 100

    average_marks = dataframe[
        subject
    ].mean()

    highest_marks = dataframe[
        subject
    ].max()

    lowest_marks = dataframe[
        subject
    ].min()

    if pass_percentage >= 85:
        status = "Good"

    elif pass_percentage >= 70:
        status = "Average"

    else:
        status = "Poor"
    return {
    "Subject": subject,
    "Topper": topper["Names"],
    "Topper Marks": highest_marks,
    "Passed": passed,
    "Failed": failed,
    "Pass %": pass_percentage,
    "Fail %": fail_percentage,
    "Average": average_marks,
    "Status": status
    }

analysis = []

for subject in subjects:
    analysis.append(
        subject_analysis(dataframe, subject)
    )

report_df = pd.DataFrame(analysis, index = [1,2,3,4,5,6])

report_df

,Subject,Topper,Topper Marks,Passed,Failed,Pass %,Fail %,Average,Status
1,Maths,Anthony,100,432,68,86.4,13.6,62.794,Good
2,Science,Alex,100,421,79,84.2,15.8,60.328,Average
3,Social_sci,Eric,100,428,72,85.6,14.4,62.026,Good
4,English,Andrea,100,439,61,87.8,12.2,61.694,Good
5,Marathi,Antonio,100,428,72,85.6,14.4,63.024,Good
6,Kannada,Allen,100,426,74,85.2,14.8,62.280,Good